import Head from 'next/head'
import { FC, PropsWithChildren } from 'react'

import styles from './Header.module.scss'

const Header: FC<PropsWithChildren> = ({ children }) => {
	return (
		<>
			<Head>
				<title>Shop у Татьяны</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header className={styles.header}>{children}</header>
		</>
	)
}

export default Header
