import React from "react";
import Head from "next/head";
import localFont from "next/font/local";
import Header from "@/components/Header";

const jostFont = localFont({
    src: [
        {
            path: '../../public/fonts/Jost-Regular.woff2',
            weight: '400',
            style: 'normal'
        },
        {
            path: '../../public/fonts/Jost-Medium.woff2',
            weight: '500',
            style: 'normal'
        },
        {
            path: '../../public/fonts/Jost-SemiBold.woff2',
            weight: '600',
            style: 'normal'
        },
    ]
})

const Layout: React.FC = ({children}) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={jostFont.className}>
                <Header />
                <main>{children}</main>
            </div>
        </>
    )
}

export default Layout